/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  jsonb,
  timestamp,
  numeric,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_contact_messages_status = pgEnum(
  "enum_contact_messages_status",
  ["new", "in-progress", "replied", "archived"],
);
export const enum_footer_social_media_links_social_media = pgEnum(
  "enum_footer_social_media_links_social_media",
  [
    "facebook",
    "gmail",
    "x",
    "medium",
    "email",
    "phone",
    "instagram",
    "linkedin",
    "youtube",
    "tiktok",
    "telegram",
    "whatsapp",
    "snapchat",
    "pinterest",
    "viber",
    "skype",
    "reddit",
    "discord",
    "github",
    "gitlab",
    "bitbucket",
    "dribbble",
    "google",
    "behance",
  ],
);

export const restaurants_details = pgTable(
  "restaurants_details",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
    value: varchar("value"),
    desc: varchar("desc"),
  },
  (columns) => ({
    _orderIdx: index("restaurants_details_order_idx").on(columns._order),
    _parentIDIdx: index("restaurants_details_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [restaurants.id],
      name: "restaurants_details_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const restaurants = pgTable(
  "restaurants",
  {
    id: serial("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    name: varchar("name").notNull(),
    description: varchar("description"),
    location: varchar("location"),
    phone: varchar("phone"),
    content: jsonb("content"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    restaurants_image_idx: index("restaurants_image_idx").on(columns.image),
    restaurants_meta_meta_image_idx: index(
      "restaurants_meta_meta_image_idx",
    ).on(columns.meta_image),
    restaurants_updated_at_idx: index("restaurants_updated_at_idx").on(
      columns.updatedAt,
    ),
    restaurants_created_at_idx: index("restaurants_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index("users_sessions_order_idx").on(columns._order),
    _parentIDIdx: index("users_sessions_parent_id_idx").on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width"),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height"),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize"),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_square_url: varchar("sizes_square_url"),
    sizes_square_width: numeric("sizes_square_width"),
    sizes_square_height: numeric("sizes_square_height"),
    sizes_square_mimeType: varchar("sizes_square_mime_type"),
    sizes_square_filesize: numeric("sizes_square_filesize"),
    sizes_square_filename: varchar("sizes_square_filename"),
    sizes_small_url: varchar("sizes_small_url"),
    sizes_small_width: numeric("sizes_small_width"),
    sizes_small_height: numeric("sizes_small_height"),
    sizes_small_mimeType: varchar("sizes_small_mime_type"),
    sizes_small_filesize: numeric("sizes_small_filesize"),
    sizes_small_filename: varchar("sizes_small_filename"),
    sizes_medium_url: varchar("sizes_medium_url"),
    sizes_medium_width: numeric("sizes_medium_width"),
    sizes_medium_height: numeric("sizes_medium_height"),
    sizes_medium_mimeType: varchar("sizes_medium_mime_type"),
    sizes_medium_filesize: numeric("sizes_medium_filesize"),
    sizes_medium_filename: varchar("sizes_medium_filename"),
    sizes_large_url: varchar("sizes_large_url"),
    sizes_large_width: numeric("sizes_large_width"),
    sizes_large_height: numeric("sizes_large_height"),
    sizes_large_mimeType: varchar("sizes_large_mime_type"),
    sizes_large_filesize: numeric("sizes_large_filesize"),
    sizes_large_filename: varchar("sizes_large_filename"),
    sizes_xlarge_url: varchar("sizes_xlarge_url"),
    sizes_xlarge_width: numeric("sizes_xlarge_width"),
    sizes_xlarge_height: numeric("sizes_xlarge_height"),
    sizes_xlarge_mimeType: varchar("sizes_xlarge_mime_type"),
    sizes_xlarge_filesize: numeric("sizes_xlarge_filesize"),
    sizes_xlarge_filename: varchar("sizes_xlarge_filename"),
    sizes_og_url: varchar("sizes_og_url"),
    sizes_og_width: numeric("sizes_og_width"),
    sizes_og_height: numeric("sizes_og_height"),
    sizes_og_mimeType: varchar("sizes_og_mime_type"),
    sizes_og_filesize: numeric("sizes_og_filesize"),
    sizes_og_filename: varchar("sizes_og_filename"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
    media_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      "media_sizes_thumbnail_sizes_thumbnail_filename_idx",
    ).on(columns.sizes_thumbnail_filename),
    media_sizes_square_sizes_square_filename_idx: index(
      "media_sizes_square_sizes_square_filename_idx",
    ).on(columns.sizes_square_filename),
    media_sizes_small_sizes_small_filename_idx: index(
      "media_sizes_small_sizes_small_filename_idx",
    ).on(columns.sizes_small_filename),
    media_sizes_medium_sizes_medium_filename_idx: index(
      "media_sizes_medium_sizes_medium_filename_idx",
    ).on(columns.sizes_medium_filename),
    media_sizes_large_sizes_large_filename_idx: index(
      "media_sizes_large_sizes_large_filename_idx",
    ).on(columns.sizes_large_filename),
    media_sizes_xlarge_sizes_xlarge_filename_idx: index(
      "media_sizes_xlarge_sizes_xlarge_filename_idx",
    ).on(columns.sizes_xlarge_filename),
    media_sizes_og_sizes_og_filename_idx: index(
      "media_sizes_og_sizes_og_filename_idx",
    ).on(columns.sizes_og_filename),
  }),
);

export const blogs = pgTable(
  "blogs",
  {
    id: serial("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    title: varchar("title").notNull(),
    desc: varchar("desc").notNull(),
    content: jsonb("content"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    blogs_image_idx: index("blogs_image_idx").on(columns.image),
    blogs_meta_meta_image_idx: index("blogs_meta_meta_image_idx").on(
      columns.meta_image,
    ),
    blogs_updated_at_idx: index("blogs_updated_at_idx").on(columns.updatedAt),
    blogs_created_at_idx: index("blogs_created_at_idx").on(columns.createdAt),
  }),
);

export const contact_messages = pgTable(
  "contact_messages",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    message: varchar("message").notNull(),
    status: enum_contact_messages_status("status").default("new"),
    confirm: boolean("confirm").notNull().default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    contact_messages_updated_at_idx: index(
      "contact_messages_updated_at_idx",
    ).on(columns.updatedAt),
    contact_messages_created_at_idx: index(
      "contact_messages_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    restaurantsID: integer("restaurants_id"),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    blogsID: integer("blogs_id"),
    "contact-messagesID": integer("contact_messages_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_restaurants_id_idx: index(
      "payload_locked_documents_rels_restaurants_id_idx",
    ).on(columns.restaurantsID),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_blogs_id_idx: index(
      "payload_locked_documents_rels_blogs_id_idx",
    ).on(columns.blogsID),
    payload_locked_documents_rels_contact_messages_id_idx: index(
      "payload_locked_documents_rels_contact_messages_id_idx",
    ).on(columns["contact-messagesID"]),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    restaurantsIdFk: foreignKey({
      columns: [columns["restaurantsID"]],
      foreignColumns: [restaurants.id],
      name: "payload_locked_documents_rels_restaurants_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    blogsIdFk: foreignKey({
      columns: [columns["blogsID"]],
      foreignColumns: [blogs.id],
      name: "payload_locked_documents_rels_blogs_fk",
    }).onDelete("cascade"),
    "contact-messagesIdFk": foreignKey({
      columns: [columns["contact-messagesID"]],
      foreignColumns: [contact_messages.id],
      name: "payload_locked_documents_rels_contact_messages_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const about_us = pgTable(
  "about_us",
  {
    id: serial("id").primaryKey(),
    hero_title: varchar("hero_title"),
    hero_description: varchar("hero_description"),
    hero_image: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    hero_ctaLink_newTab: boolean("hero_cta_link_new_tab"),
    hero_ctaLink_url: varchar("hero_cta_link_url").notNull(),
    hero_ctaLink_label: varchar("hero_cta_link_label"),
    hero_enable: boolean("hero_enable").default(true),
    content: jsonb("content"),
    ctaSection_label: varchar("cta_section_label"),
    ctaSection_title: varchar("cta_section_title"),
    ctaSection_description: varchar("cta_section_description"),
    ctaSection_image: integer("cta_section_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    ctaSection_link_newTab: boolean("cta_section_link_new_tab"),
    ctaSection_link_url: varchar("cta_section_link_url").notNull(),
    ctaSection_link_label: varchar("cta_section_link_label"),
    ctaSection_enable: boolean("cta_section_enable").default(true),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    about_us_hero_hero_image_idx: index("about_us_hero_hero_image_idx").on(
      columns.hero_image,
    ),
    about_us_cta_section_cta_section_image_idx: index(
      "about_us_cta_section_cta_section_image_idx",
    ).on(columns.ctaSection_image),
    about_us_meta_meta_image_idx: index("about_us_meta_meta_image_idx").on(
      columns.meta_image,
    ),
  }),
);

export const home = pgTable(
  "home",
  {
    id: serial("id").primaryKey(),
    restaurantsCarousel_title: varchar("restaurants_carousel_title"),
    restaurantsCarousel_enable: boolean("restaurants_carousel_enable").default(
      false,
    ),
    blogs_title: varchar("blogs_title"),
    blogs_description: varchar("blogs_description"),
    blogs_enable: boolean("blogs_enable").default(false),
    ctaSection_label: varchar("cta_section_label"),
    ctaSection_title: varchar("cta_section_title"),
    ctaSection_description: varchar("cta_section_description"),
    ctaSection_ctaLink_newTab: boolean("cta_section_cta_link_new_tab"),
    ctaSection_ctaLink_url: varchar("cta_section_cta_link_url").notNull(),
    ctaSection_ctaLink_label: varchar("cta_section_cta_link_label"),
    ctaSection_image: integer("cta_section_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    ctaSection_enable: boolean("cta_section_enable").default(false),
    topRestaurants_title: varchar("top_restaurants_title"),
    topRestaurants_description: varchar("top_restaurants_description"),
    topRestaurants_enable: boolean("top_restaurants_enable").default(false),
    contactUs_label: varchar("contact_us_label"),
    contactUs_title: varchar("contact_us_title"),
    contactUs_description: varchar("contact_us_description"),
    contactUs_enable: boolean("contact_us_enable").default(false),
    contactUs_contacts_phone_ctaText: varchar(
      "contact_us_contacts_phone_cta_text",
    ).default("Call us"),
    contactUs_contacts_phone_number: varchar(
      "contact_us_contacts_phone_number",
    ).default("+1 400 500 600"),
    contactUs_contacts_phone_placeholder: varchar(
      "contact_us_contacts_phone_placeholder",
    ),
    contactUs_contacts_emailAddress_ctaText: varchar(
      "contact_us_contacts_email_address_cta_text",
    ).default("Write an email"),
    contactUs_contacts_emailAddress_email: varchar(
      "contact_us_contacts_email_address_email",
    ).default("hello@example.com"),
    contactUs_contacts_emailAddress_placeholder: varchar(
      "contact_us_contacts_email_address_placeholder",
    ),
    contactUs_contacts_location_ctaText: varchar(
      "contact_us_contacts_location_cta_text",
    ).default("Visit our office"),
    contactUs_contacts_location_url: varchar(
      "contact_us_contacts_location_url",
    ).default("/"),
    contactUs_contacts_location_placeholder: varchar(
      "contact_us_contacts_location_placeholder",
    ).default("192 Griffin Street, Gilbert, AZ 32521"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    home_cta_section_cta_section_image_idx: index(
      "home_cta_section_cta_section_image_idx",
    ).on(columns.ctaSection_image),
    home_meta_meta_image_idx: index("home_meta_meta_image_idx").on(
      columns.meta_image,
    ),
  }),
);

export const home_rels = pgTable(
  "home_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    restaurantsID: integer("restaurants_id"),
  },
  (columns) => ({
    order: index("home_rels_order_idx").on(columns.order),
    parentIdx: index("home_rels_parent_idx").on(columns.parent),
    pathIdx: index("home_rels_path_idx").on(columns.path),
    home_rels_restaurants_id_idx: index("home_rels_restaurants_id_idx").on(
      columns.restaurantsID,
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [home.id],
      name: "home_rels_parent_fk",
    }).onDelete("cascade"),
    restaurantsIdFk: foreignKey({
      columns: [columns["restaurantsID"]],
      foreignColumns: [restaurants.id],
      name: "home_rels_restaurants_fk",
    }).onDelete("cascade"),
  }),
);

export const privacy_policy = pgTable(
  "privacy_policy",
  {
    id: serial("id").primaryKey(),
    content: jsonb("content"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    privacy_policy_meta_meta_image_idx: index(
      "privacy_policy_meta_meta_image_idx",
    ).on(columns.meta_image),
  }),
);

export const terms_of_service = pgTable(
  "terms_of_service",
  {
    id: serial("id").primaryKey(),
    content: jsonb("content"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    terms_of_service_meta_meta_image_idx: index(
      "terms_of_service_meta_meta_image_idx",
    ).on(columns.meta_image),
  }),
);

export const cookies_settings = pgTable(
  "cookies_settings",
  {
    id: serial("id").primaryKey(),
    content: jsonb("content"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    cookies_settings_meta_meta_image_idx: index(
      "cookies_settings_meta_meta_image_idx",
    ).on(columns.meta_image),
  }),
);

export const footer_social_media_links = pgTable(
  "footer_social_media_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    socialMedia:
      enum_footer_social_media_links_social_media("social_media").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => ({
    _orderIdx: index("footer_social_media_links_order_idx").on(columns._order),
    _parentIDIdx: index("footer_social_media_links_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_social_media_links_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const footer = pgTable("footer", {
  id: serial("id").primaryKey(),
  copyrightText: varchar("copyright_text").default(
    "Copyright 2025 © Best Pizza Malta",
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const site = pgTable(
  "site",
  {
    id: serial("id").primaryKey(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    favicon: integer("favicon_id").references(() => media.id, {
      onDelete: "set null",
    }),
    googleVerificationCode: varchar("google_verification_code"),
    googleTagManagerId: varchar("google_tag_manager_id"),
    googleAnalyticsId: varchar("google_analytics_id"),
    cookieConsentBannerEnabled: boolean("cookie_consent_banner_enabled"),
    acceptButtonLabel: varchar("accept_button_label")
      .notNull()
      .default("Accept All"),
    rejectButtonLabel: varchar("reject_button_label")
      .notNull()
      .default("Reject All"),
    cookieConsentBannerContent: jsonb("cookie_consent_banner_content"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    site_logo_idx: index("site_logo_idx").on(columns.logo),
    site_favicon_idx: index("site_favicon_idx").on(columns.favicon),
  }),
);

export const relations_restaurants_details = relations(
  restaurants_details,
  ({ one }) => ({
    _parentID: one(restaurants, {
      fields: [restaurants_details._parentID],
      references: [restaurants.id],
      relationName: "details",
    }),
  }),
);
export const relations_restaurants = relations(
  restaurants,
  ({ one, many }) => ({
    image: one(media, {
      fields: [restaurants.image],
      references: [media.id],
      relationName: "image",
    }),
    details: many(restaurants_details, {
      relationName: "details",
    }),
    meta_image: one(media, {
      fields: [restaurants.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_blogs = relations(blogs, ({ one }) => ({
  image: one(media, {
    fields: [blogs.image],
    references: [media.id],
    relationName: "image",
  }),
  meta_image: one(media, {
    fields: [blogs.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
}));
export const relations_contact_messages = relations(
  contact_messages,
  () => ({}),
);
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    restaurantsID: one(restaurants, {
      fields: [payload_locked_documents_rels.restaurantsID],
      references: [restaurants.id],
      relationName: "restaurants",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    blogsID: one(blogs, {
      fields: [payload_locked_documents_rels.blogsID],
      references: [blogs.id],
      relationName: "blogs",
    }),
    "contact-messagesID": one(contact_messages, {
      fields: [payload_locked_documents_rels["contact-messagesID"]],
      references: [contact_messages.id],
      relationName: "contact-messages",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_about_us = relations(about_us, ({ one }) => ({
  hero_image: one(media, {
    fields: [about_us.hero_image],
    references: [media.id],
    relationName: "hero_image",
  }),
  ctaSection_image: one(media, {
    fields: [about_us.ctaSection_image],
    references: [media.id],
    relationName: "ctaSection_image",
  }),
  meta_image: one(media, {
    fields: [about_us.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
}));
export const relations_home_rels = relations(home_rels, ({ one }) => ({
  parent: one(home, {
    fields: [home_rels.parent],
    references: [home.id],
    relationName: "_rels",
  }),
  restaurantsID: one(restaurants, {
    fields: [home_rels.restaurantsID],
    references: [restaurants.id],
    relationName: "restaurants",
  }),
}));
export const relations_home = relations(home, ({ one, many }) => ({
  ctaSection_image: one(media, {
    fields: [home.ctaSection_image],
    references: [media.id],
    relationName: "ctaSection_image",
  }),
  meta_image: one(media, {
    fields: [home.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
  _rels: many(home_rels, {
    relationName: "_rels",
  }),
}));
export const relations_privacy_policy = relations(
  privacy_policy,
  ({ one }) => ({
    meta_image: one(media, {
      fields: [privacy_policy.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_terms_of_service = relations(
  terms_of_service,
  ({ one }) => ({
    meta_image: one(media, {
      fields: [terms_of_service.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_cookies_settings = relations(
  cookies_settings,
  ({ one }) => ({
    meta_image: one(media, {
      fields: [cookies_settings.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_footer_social_media_links = relations(
  footer_social_media_links,
  ({ one }) => ({
    _parentID: one(footer, {
      fields: [footer_social_media_links._parentID],
      references: [footer.id],
      relationName: "socialMediaLinks",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  socialMediaLinks: many(footer_social_media_links, {
    relationName: "socialMediaLinks",
  }),
}));
export const relations_site = relations(site, ({ one }) => ({
  logo: one(media, {
    fields: [site.logo],
    references: [media.id],
    relationName: "logo",
  }),
  favicon: one(media, {
    fields: [site.favicon],
    references: [media.id],
    relationName: "favicon",
  }),
}));

type DatabaseSchema = {
  enum_contact_messages_status: typeof enum_contact_messages_status;
  enum_footer_social_media_links_social_media: typeof enum_footer_social_media_links_social_media;
  restaurants_details: typeof restaurants_details;
  restaurants: typeof restaurants;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  blogs: typeof blogs;
  contact_messages: typeof contact_messages;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  about_us: typeof about_us;
  home: typeof home;
  home_rels: typeof home_rels;
  privacy_policy: typeof privacy_policy;
  terms_of_service: typeof terms_of_service;
  cookies_settings: typeof cookies_settings;
  footer_social_media_links: typeof footer_social_media_links;
  footer: typeof footer;
  site: typeof site;
  relations_restaurants_details: typeof relations_restaurants_details;
  relations_restaurants: typeof relations_restaurants;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_blogs: typeof relations_blogs;
  relations_contact_messages: typeof relations_contact_messages;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_about_us: typeof relations_about_us;
  relations_home_rels: typeof relations_home_rels;
  relations_home: typeof relations_home;
  relations_privacy_policy: typeof relations_privacy_policy;
  relations_terms_of_service: typeof relations_terms_of_service;
  relations_cookies_settings: typeof relations_cookies_settings;
  relations_footer_social_media_links: typeof relations_footer_social_media_links;
  relations_footer: typeof relations_footer;
  relations_site: typeof relations_site;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
